// PhantomPrint — Realistic Device Profile Database
// 25+ internally-consistent device profiles covering realistic market distribution
// Each profile contains ALL spoofable properties as a coherent set

var PhantomProfiles = (function() {
  'use strict';

  const PROFILES = [
    // ═══════════════════════════════════════════════════════
    // WINDOWS + NVIDIA GPUs
    // ═══════════════════════════════════════════════════════
    {
      id: 'win_chrome_rtx3060_1080p',
      os: 'Windows',
      platform: 'Win32',
      userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36',
      appVersion: '5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36',
      vendor: 'Google Inc.',
      hardwareConcurrency: 12,
      deviceMemory: 16,
      languages: ['en-US', 'en'],
      language: 'en-US',
      maxTouchPoints: 0,
      colorDepth: 24,
      pixelDepth: 24,
      screen: { width: 1920, height: 1080, availWidth: 1920, availHeight: 1040 },
      devicePixelRatio: 1,
      gpu: {
        vendor: 'Google Inc. (NVIDIA)',
        renderer: 'ANGLE (NVIDIA, NVIDIA GeForce RTX 3060 Direct3D11 vs_5_0 ps_5_0, D3D11)',
        maxTextureSize: 16384,
        maxViewportDims: [32768, 32768],
        maxVertexAttribs: 16,
        maxVertexUniformVectors: 4096,
        maxVaryingVectors: 32,
        maxCombinedTextureImageUnits: 32,
        maxVertexTextureImageUnits: 16,
        maxTextureImageUnits: 16,
        maxFragmentUniformVectors: 1024,
        maxCubeMapTextureSize: 16384,
        maxRenderbufferSize: 16384,
        aliasedLineWidthRange: [1, 1],
        aliasedPointSizeRange: [1, 1024]
      },
      timezone: { offset: -300, zone: 'America/New_York' },
      doNotTrack: null,
      connection: { effectiveType: '4g', rtt: 50, downlink: 10 },
      fonts: ['Arial', 'Arial Black', 'Calibri', 'Cambria', 'Comic Sans MS', 'Consolas', 'Courier New', 'Georgia', 'Impact', 'Lucida Console', 'Segoe UI', 'Tahoma', 'Times New Roman', 'Trebuchet MS', 'Verdana'],
      voiceCount: 5,
      mediaDevices: { audioinput: 1, videoinput: 1, audiooutput: 2 },
      battery: { charging: true, chargingTime: 0, dischargingTime: Infinity, level: 1.0 },
      audioParams: { baseLatency: 0.01, outputLatency: 0.01, sampleRate: 48000 }
    },
    {
      id: 'win_chrome_rtx4070_1440p',
      os: 'Windows',
      platform: 'Win32',
      userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36',
      appVersion: '5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36',
      vendor: 'Google Inc.',
      hardwareConcurrency: 16,
      deviceMemory: 32,
      languages: ['en-US', 'en'],
      language: 'en-US',
      maxTouchPoints: 0,
      colorDepth: 24,
      pixelDepth: 24,
      screen: { width: 2560, height: 1440, availWidth: 2560, availHeight: 1400 },
      devicePixelRatio: 1,
      gpu: {
        vendor: 'Google Inc. (NVIDIA)',
        renderer: 'ANGLE (NVIDIA, NVIDIA GeForce RTX 4070 Direct3D11 vs_5_0 ps_5_0, D3D11)',
        maxTextureSize: 16384,
        maxViewportDims: [32768, 32768],
        maxVertexAttribs: 16,
        maxVertexUniformVectors: 4096,
        maxVaryingVectors: 32,
        maxCombinedTextureImageUnits: 32,
        maxVertexTextureImageUnits: 16,
        maxTextureImageUnits: 16,
        maxFragmentUniformVectors: 1024,
        maxCubeMapTextureSize: 16384,
        maxRenderbufferSize: 16384,
        aliasedLineWidthRange: [1, 1],
        aliasedPointSizeRange: [1, 1024]
      },
      timezone: { offset: -360, zone: 'America/Chicago' },
      doNotTrack: '1',
      connection: { effectiveType: '4g', rtt: 50, downlink: 10 },
      fonts: ['Arial', 'Arial Black', 'Calibri', 'Cambria', 'Comic Sans MS', 'Consolas', 'Courier New', 'Georgia', 'Impact', 'Lucida Console', 'Segoe UI', 'Tahoma', 'Times New Roman', 'Trebuchet MS', 'Verdana'],
      voiceCount: 5,
      mediaDevices: { audioinput: 2, videoinput: 1, audiooutput: 3 },
      battery: { charging: true, chargingTime: 0, dischargingTime: Infinity, level: 1.0 },
      audioParams: { baseLatency: 0.01, outputLatency: 0.01, sampleRate: 48000 }
    },
    {
      id: 'win_chrome_gtx1660_1080p',
      os: 'Windows',
      platform: 'Win32',
      userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36',
      appVersion: '5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36',
      vendor: 'Google Inc.',
      hardwareConcurrency: 8,
      deviceMemory: 16,
      languages: ['en-US', 'en'],
      language: 'en-US',
      maxTouchPoints: 0,
      colorDepth: 24,
      pixelDepth: 24,
      screen: { width: 1920, height: 1080, availWidth: 1920, availHeight: 1040 },
      devicePixelRatio: 1,
      gpu: {
        vendor: 'Google Inc. (NVIDIA)',
        renderer: 'ANGLE (NVIDIA, NVIDIA GeForce GTX 1660 SUPER Direct3D11 vs_5_0 ps_5_0, D3D11)',
        maxTextureSize: 16384,
        maxViewportDims: [32768, 32768],
        maxVertexAttribs: 16,
        maxVertexUniformVectors: 4096,
        maxVaryingVectors: 32,
        maxCombinedTextureImageUnits: 32,
        maxVertexTextureImageUnits: 16,
        maxTextureImageUnits: 16,
        maxFragmentUniformVectors: 1024,
        maxCubeMapTextureSize: 16384,
        maxRenderbufferSize: 16384,
        aliasedLineWidthRange: [1, 1],
        aliasedPointSizeRange: [1, 1024]
      },
      timezone: { offset: -480, zone: 'America/Los_Angeles' },
      doNotTrack: null,
      connection: { effectiveType: '4g', rtt: 100, downlink: 5 },
      fonts: ['Arial', 'Calibri', 'Cambria', 'Comic Sans MS', 'Consolas', 'Courier New', 'Georgia', 'Impact', 'Segoe UI', 'Tahoma', 'Times New Roman', 'Trebuchet MS', 'Verdana'],
      voiceCount: 5,
      mediaDevices: { audioinput: 1, videoinput: 1, audiooutput: 1 },
      battery: { charging: false, chargingTime: Infinity, dischargingTime: 14400, level: 0.72 },
      audioParams: { baseLatency: 0.01, outputLatency: 0.01, sampleRate: 44100 }
    },
    {
      id: 'win_chrome_rtx3080_4k',
      os: 'Windows',
      platform: 'Win32',
      userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36',
      appVersion: '5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36',
      vendor: 'Google Inc.',
      hardwareConcurrency: 16,
      deviceMemory: 32,
      languages: ['en-US', 'en'],
      language: 'en-US',
      maxTouchPoints: 0,
      colorDepth: 32,
      pixelDepth: 32,
      screen: { width: 3840, height: 2160, availWidth: 3840, availHeight: 2120 },
      devicePixelRatio: 1.5,
      gpu: {
        vendor: 'Google Inc. (NVIDIA)',
        renderer: 'ANGLE (NVIDIA, NVIDIA GeForce RTX 3080 Direct3D11 vs_5_0 ps_5_0, D3D11)',
        maxTextureSize: 16384,
        maxViewportDims: [32768, 32768],
        maxVertexAttribs: 16,
        maxVertexUniformVectors: 4096,
        maxVaryingVectors: 32,
        maxCombinedTextureImageUnits: 32,
        maxVertexTextureImageUnits: 16,
        maxTextureImageUnits: 16,
        maxFragmentUniformVectors: 1024,
        maxCubeMapTextureSize: 16384,
        maxRenderbufferSize: 16384,
        aliasedLineWidthRange: [1, 1],
        aliasedPointSizeRange: [1, 1024]
      },
      timezone: { offset: -300, zone: 'America/New_York' },
      doNotTrack: null,
      connection: { effectiveType: '4g', rtt: 50, downlink: 10 },
      fonts: ['Arial', 'Arial Black', 'Calibri', 'Cambria', 'Comic Sans MS', 'Consolas', 'Courier New', 'Georgia', 'Impact', 'Lucida Console', 'Segoe UI', 'Tahoma', 'Times New Roman', 'Trebuchet MS', 'Verdana'],
      voiceCount: 5,
      mediaDevices: { audioinput: 2, videoinput: 1, audiooutput: 2 },
      battery: { charging: true, chargingTime: 0, dischargingTime: Infinity, level: 1.0 },
      audioParams: { baseLatency: 0.01, outputLatency: 0.01, sampleRate: 48000 }
    },

    // ═══════════════════════════════════════════════════════
    // WINDOWS + AMD GPUs
    // ═══════════════════════════════════════════════════════
    {
      id: 'win_chrome_rx580_1080p',
      os: 'Windows',
      platform: 'Win32',
      userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36',
      appVersion: '5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36',
      vendor: 'Google Inc.',
      hardwareConcurrency: 8,
      deviceMemory: 8,
      languages: ['en-US', 'en'],
      language: 'en-US',
      maxTouchPoints: 0,
      colorDepth: 24,
      pixelDepth: 24,
      screen: { width: 1920, height: 1080, availWidth: 1920, availHeight: 1040 },
      devicePixelRatio: 1,
      gpu: {
        vendor: 'Google Inc. (AMD)',
        renderer: 'ANGLE (AMD, AMD Radeon RX 580 Direct3D11 vs_5_0 ps_5_0, D3D11)',
        maxTextureSize: 16384,
        maxViewportDims: [16384, 16384],
        maxVertexAttribs: 16,
        maxVertexUniformVectors: 4096,
        maxVaryingVectors: 32,
        maxCombinedTextureImageUnits: 32,
        maxVertexTextureImageUnits: 16,
        maxTextureImageUnits: 16,
        maxFragmentUniformVectors: 1024,
        maxCubeMapTextureSize: 16384,
        maxRenderbufferSize: 16384,
        aliasedLineWidthRange: [1, 1],
        aliasedPointSizeRange: [1, 1024]
      },
      timezone: { offset: -420, zone: 'America/Denver' },
      doNotTrack: null,
      connection: { effectiveType: '4g', rtt: 100, downlink: 5 },
      fonts: ['Arial', 'Calibri', 'Cambria', 'Comic Sans MS', 'Consolas', 'Courier New', 'Georgia', 'Impact', 'Segoe UI', 'Tahoma', 'Times New Roman', 'Trebuchet MS', 'Verdana'],
      voiceCount: 5,
      mediaDevices: { audioinput: 1, videoinput: 0, audiooutput: 1 },
      battery: { charging: true, chargingTime: 0, dischargingTime: Infinity, level: 1.0 },
      audioParams: { baseLatency: 0.01, outputLatency: 0.02, sampleRate: 44100 }
    },
    {
      id: 'win_chrome_rx6700xt_1440p',
      os: 'Windows',
      platform: 'Win32',
      userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36',
      appVersion: '5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36',
      vendor: 'Google Inc.',
      hardwareConcurrency: 12,
      deviceMemory: 16,
      languages: ['en-US', 'en'],
      language: 'en-US',
      maxTouchPoints: 0,
      colorDepth: 24,
      pixelDepth: 24,
      screen: { width: 2560, height: 1440, availWidth: 2560, availHeight: 1400 },
      devicePixelRatio: 1,
      gpu: {
        vendor: 'Google Inc. (AMD)',
        renderer: 'ANGLE (AMD, AMD Radeon RX 6700 XT Direct3D11 vs_5_0 ps_5_0, D3D11)',
        maxTextureSize: 16384,
        maxViewportDims: [16384, 16384],
        maxVertexAttribs: 16,
        maxVertexUniformVectors: 4096,
        maxVaryingVectors: 32,
        maxCombinedTextureImageUnits: 32,
        maxVertexTextureImageUnits: 16,
        maxTextureImageUnits: 16,
        maxFragmentUniformVectors: 1024,
        maxCubeMapTextureSize: 16384,
        maxRenderbufferSize: 16384,
        aliasedLineWidthRange: [1, 1],
        aliasedPointSizeRange: [1, 1024]
      },
      timezone: { offset: -300, zone: 'America/New_York' },
      doNotTrack: null,
      connection: { effectiveType: '4g', rtt: 50, downlink: 10 },
      fonts: ['Arial', 'Arial Black', 'Calibri', 'Cambria', 'Comic Sans MS', 'Consolas', 'Courier New', 'Georgia', 'Impact', 'Lucida Console', 'Segoe UI', 'Tahoma', 'Times New Roman', 'Trebuchet MS', 'Verdana'],
      voiceCount: 5,
      mediaDevices: { audioinput: 1, videoinput: 1, audiooutput: 2 },
      battery: { charging: true, chargingTime: 0, dischargingTime: Infinity, level: 1.0 },
      audioParams: { baseLatency: 0.01, outputLatency: 0.01, sampleRate: 48000 }
    },
    {
      id: 'win_chrome_rx7900xtx_4k',
      os: 'Windows',
      platform: 'Win32',
      userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36',
      appVersion: '5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36',
      vendor: 'Google Inc.',
      hardwareConcurrency: 16,
      deviceMemory: 32,
      languages: ['en-US'],
      language: 'en-US',
      maxTouchPoints: 0,
      colorDepth: 32,
      pixelDepth: 32,
      screen: { width: 3840, height: 2160, availWidth: 3840, availHeight: 2120 },
      devicePixelRatio: 1.5,
      gpu: {
        vendor: 'Google Inc. (AMD)',
        renderer: 'ANGLE (AMD, AMD Radeon RX 7900 XTX Direct3D11 vs_5_0 ps_5_0, D3D11)',
        maxTextureSize: 16384,
        maxViewportDims: [16384, 16384],
        maxVertexAttribs: 16,
        maxVertexUniformVectors: 4096,
        maxVaryingVectors: 32,
        maxCombinedTextureImageUnits: 32,
        maxVertexTextureImageUnits: 16,
        maxTextureImageUnits: 16,
        maxFragmentUniformVectors: 1024,
        maxCubeMapTextureSize: 16384,
        maxRenderbufferSize: 16384,
        aliasedLineWidthRange: [1, 1],
        aliasedPointSizeRange: [1, 1024]
      },
      timezone: { offset: -480, zone: 'America/Los_Angeles' },
      doNotTrack: '1',
      connection: { effectiveType: '4g', rtt: 50, downlink: 10 },
      fonts: ['Arial', 'Arial Black', 'Calibri', 'Cambria', 'Comic Sans MS', 'Consolas', 'Courier New', 'Georgia', 'Impact', 'Lucida Console', 'Segoe UI', 'Tahoma', 'Times New Roman', 'Trebuchet MS', 'Verdana'],
      voiceCount: 5,
      mediaDevices: { audioinput: 2, videoinput: 1, audiooutput: 3 },
      battery: { charging: true, chargingTime: 0, dischargingTime: Infinity, level: 1.0 },
      audioParams: { baseLatency: 0.005, outputLatency: 0.01, sampleRate: 48000 }
    },

    // ═══════════════════════════════════════════════════════
    // WINDOWS + INTEL GPUs
    // ═══════════════════════════════════════════════════════
    {
      id: 'win_chrome_uhd630_1080p',
      os: 'Windows',
      platform: 'Win32',
      userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36',
      appVersion: '5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36',
      vendor: 'Google Inc.',
      hardwareConcurrency: 8,
      deviceMemory: 8,
      languages: ['en-US', 'en'],
      language: 'en-US',
      maxTouchPoints: 0,
      colorDepth: 24,
      pixelDepth: 24,
      screen: { width: 1920, height: 1080, availWidth: 1920, availHeight: 1040 },
      devicePixelRatio: 1,
      gpu: {
        vendor: 'Google Inc. (Intel)',
        renderer: 'ANGLE (Intel, Intel(R) UHD Graphics 630 Direct3D11 vs_5_0 ps_5_0, D3D11)',
        maxTextureSize: 16384,
        maxViewportDims: [16384, 16384],
        maxVertexAttribs: 16,
        maxVertexUniformVectors: 4096,
        maxVaryingVectors: 32,
        maxCombinedTextureImageUnits: 32,
        maxVertexTextureImageUnits: 16,
        maxTextureImageUnits: 16,
        maxFragmentUniformVectors: 1024,
        maxCubeMapTextureSize: 16384,
        maxRenderbufferSize: 16384,
        aliasedLineWidthRange: [1, 1],
        aliasedPointSizeRange: [1, 1024]
      },
      timezone: { offset: -300, zone: 'America/New_York' },
      doNotTrack: null,
      connection: { effectiveType: '4g', rtt: 100, downlink: 5 },
      fonts: ['Arial', 'Calibri', 'Cambria', 'Comic Sans MS', 'Consolas', 'Courier New', 'Georgia', 'Impact', 'Segoe UI', 'Tahoma', 'Times New Roman', 'Trebuchet MS', 'Verdana'],
      voiceCount: 5,
      mediaDevices: { audioinput: 1, videoinput: 1, audiooutput: 1 },
      battery: { charging: false, chargingTime: Infinity, dischargingTime: 18000, level: 0.85 },
      audioParams: { baseLatency: 0.01, outputLatency: 0.02, sampleRate: 44100 }
    },
    {
      id: 'win_chrome_iris_xe_1080p',
      os: 'Windows',
      platform: 'Win32',
      userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36',
      appVersion: '5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36',
      vendor: 'Google Inc.',
      hardwareConcurrency: 8,
      deviceMemory: 16,
      languages: ['en-US', 'en'],
      language: 'en-US',
      maxTouchPoints: 10,
      colorDepth: 24,
      pixelDepth: 24,
      screen: { width: 1920, height: 1080, availWidth: 1920, availHeight: 1040 },
      devicePixelRatio: 1.25,
      gpu: {
        vendor: 'Google Inc. (Intel)',
        renderer: 'ANGLE (Intel, Intel(R) Iris(R) Xe Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)',
        maxTextureSize: 16384,
        maxViewportDims: [16384, 16384],
        maxVertexAttribs: 16,
        maxVertexUniformVectors: 4096,
        maxVaryingVectors: 32,
        maxCombinedTextureImageUnits: 32,
        maxVertexTextureImageUnits: 16,
        maxTextureImageUnits: 16,
        maxFragmentUniformVectors: 1024,
        maxCubeMapTextureSize: 16384,
        maxRenderbufferSize: 16384,
        aliasedLineWidthRange: [1, 1],
        aliasedPointSizeRange: [1, 1024]
      },
      timezone: { offset: 0, zone: 'Europe/London' },
      doNotTrack: null,
      connection: { effectiveType: '4g', rtt: 50, downlink: 10 },
      fonts: ['Arial', 'Calibri', 'Cambria', 'Comic Sans MS', 'Consolas', 'Courier New', 'Georgia', 'Impact', 'Segoe UI', 'Tahoma', 'Times New Roman', 'Trebuchet MS', 'Verdana'],
      voiceCount: 5,
      mediaDevices: { audioinput: 1, videoinput: 1, audiooutput: 2 },
      battery: { charging: false, chargingTime: Infinity, dischargingTime: 21600, level: 0.65 },
      audioParams: { baseLatency: 0.01, outputLatency: 0.01, sampleRate: 48000 }
    },
    {
      id: 'win_chrome_uhd770_1366',
      os: 'Windows',
      platform: 'Win32',
      userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36',
      appVersion: '5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36',
      vendor: 'Google Inc.',
      hardwareConcurrency: 4,
      deviceMemory: 8,
      languages: ['en-US', 'en'],
      language: 'en-US',
      maxTouchPoints: 0,
      colorDepth: 24,
      pixelDepth: 24,
      screen: { width: 1366, height: 768, availWidth: 1366, availHeight: 728 },
      devicePixelRatio: 1,
      gpu: {
        vendor: 'Google Inc. (Intel)',
        renderer: 'ANGLE (Intel, Intel(R) UHD Graphics 770 Direct3D11 vs_5_0 ps_5_0, D3D11)',
        maxTextureSize: 16384,
        maxViewportDims: [16384, 16384],
        maxVertexAttribs: 16,
        maxVertexUniformVectors: 4096,
        maxVaryingVectors: 32,
        maxCombinedTextureImageUnits: 32,
        maxVertexTextureImageUnits: 16,
        maxTextureImageUnits: 16,
        maxFragmentUniformVectors: 1024,
        maxCubeMapTextureSize: 16384,
        maxRenderbufferSize: 16384,
        aliasedLineWidthRange: [1, 1],
        aliasedPointSizeRange: [1, 1024]
      },
      timezone: { offset: -360, zone: 'America/Chicago' },
      doNotTrack: null,
      connection: { effectiveType: '4g', rtt: 150, downlink: 1.5 },
      fonts: ['Arial', 'Calibri', 'Cambria', 'Comic Sans MS', 'Consolas', 'Courier New', 'Georgia', 'Impact', 'Segoe UI', 'Tahoma', 'Times New Roman', 'Trebuchet MS', 'Verdana'],
      voiceCount: 5,
      mediaDevices: { audioinput: 1, videoinput: 0, audiooutput: 1 },
      battery: { charging: true, chargingTime: 3600, dischargingTime: Infinity, level: 0.55 },
      audioParams: { baseLatency: 0.01, outputLatency: 0.02, sampleRate: 44100 }
    },

    // ═══════════════════════════════════════════════════════
    // WINDOWS — Other resolutions and configs
    // ═══════════════════════════════════════════════════════
    {
      id: 'win_chrome_rtx3070_1536',
      os: 'Windows',
      platform: 'Win32',
      userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36',
      appVersion: '5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36',
      vendor: 'Google Inc.',
      hardwareConcurrency: 12,
      deviceMemory: 16,
      languages: ['de-DE', 'de', 'en-US', 'en'],
      language: 'de-DE',
      maxTouchPoints: 0,
      colorDepth: 24,
      pixelDepth: 24,
      screen: { width: 1536, height: 864, availWidth: 1536, availHeight: 824 },
      devicePixelRatio: 1.25,
      gpu: {
        vendor: 'Google Inc. (NVIDIA)',
        renderer: 'ANGLE (NVIDIA, NVIDIA GeForce RTX 3070 Direct3D11 vs_5_0 ps_5_0, D3D11)',
        maxTextureSize: 16384,
        maxViewportDims: [32768, 32768],
        maxVertexAttribs: 16,
        maxVertexUniformVectors: 4096,
        maxVaryingVectors: 32,
        maxCombinedTextureImageUnits: 32,
        maxVertexTextureImageUnits: 16,
        maxTextureImageUnits: 16,
        maxFragmentUniformVectors: 1024,
        maxCubeMapTextureSize: 16384,
        maxRenderbufferSize: 16384,
        aliasedLineWidthRange: [1, 1],
        aliasedPointSizeRange: [1, 1024]
      },
      timezone: { offset: -60, zone: 'Europe/Berlin' },
      doNotTrack: null,
      connection: { effectiveType: '4g', rtt: 50, downlink: 10 },
      fonts: ['Arial', 'Arial Black', 'Calibri', 'Cambria', 'Comic Sans MS', 'Consolas', 'Courier New', 'Georgia', 'Impact', 'Lucida Console', 'Segoe UI', 'Tahoma', 'Times New Roman', 'Trebuchet MS', 'Verdana'],
      voiceCount: 5,
      mediaDevices: { audioinput: 1, videoinput: 1, audiooutput: 2 },
      battery: { charging: true, chargingTime: 0, dischargingTime: Infinity, level: 1.0 },
      audioParams: { baseLatency: 0.01, outputLatency: 0.01, sampleRate: 48000 }
    },
    {
      id: 'win_chrome_gtx1050_fr',
      os: 'Windows',
      platform: 'Win32',
      userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36',
      appVersion: '5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36',
      vendor: 'Google Inc.',
      hardwareConcurrency: 4,
      deviceMemory: 8,
      languages: ['fr-FR', 'fr', 'en-US'],
      language: 'fr-FR',
      maxTouchPoints: 0,
      colorDepth: 24,
      pixelDepth: 24,
      screen: { width: 1920, height: 1080, availWidth: 1920, availHeight: 1040 },
      devicePixelRatio: 1,
      gpu: {
        vendor: 'Google Inc. (NVIDIA)',
        renderer: 'ANGLE (NVIDIA, NVIDIA GeForce GTX 1050 Ti Direct3D11 vs_5_0 ps_5_0, D3D11)',
        maxTextureSize: 16384,
        maxViewportDims: [32768, 32768],
        maxVertexAttribs: 16,
        maxVertexUniformVectors: 4096,
        maxVaryingVectors: 32,
        maxCombinedTextureImageUnits: 32,
        maxVertexTextureImageUnits: 16,
        maxTextureImageUnits: 16,
        maxFragmentUniformVectors: 1024,
        maxCubeMapTextureSize: 16384,
        maxRenderbufferSize: 16384,
        aliasedLineWidthRange: [1, 1],
        aliasedPointSizeRange: [1, 1024]
      },
      timezone: { offset: -60, zone: 'Europe/Paris' },
      doNotTrack: '1',
      connection: { effectiveType: '4g', rtt: 100, downlink: 5 },
      fonts: ['Arial', 'Calibri', 'Cambria', 'Comic Sans MS', 'Consolas', 'Courier New', 'Georgia', 'Impact', 'Segoe UI', 'Tahoma', 'Times New Roman', 'Trebuchet MS', 'Verdana'],
      voiceCount: 5,
      mediaDevices: { audioinput: 1, videoinput: 1, audiooutput: 1 },
      battery: { charging: false, chargingTime: Infinity, dischargingTime: 10800, level: 0.42 },
      audioParams: { baseLatency: 0.01, outputLatency: 0.02, sampleRate: 44100 }
    },

    // ═══════════════════════════════════════════════════════
    // macOS + Apple Silicon
    // ═══════════════════════════════════════════════════════
    {
      id: 'mac_chrome_m1_retina',
      os: 'macOS',
      platform: 'MacIntel',
      userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36',
      appVersion: '5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36',
      vendor: 'Google Inc.',
      hardwareConcurrency: 8,
      deviceMemory: 8,
      languages: ['en-US', 'en'],
      language: 'en-US',
      maxTouchPoints: 0,
      colorDepth: 30,
      pixelDepth: 30,
      screen: { width: 1920, height: 1080, availWidth: 1920, availHeight: 1055 },
      devicePixelRatio: 2,
      gpu: {
        vendor: 'Google Inc. (Apple)',
        renderer: 'ANGLE (Apple, Apple M1, OpenGL 4.1)',
        maxTextureSize: 16384,
        maxViewportDims: [16384, 16384],
        maxVertexAttribs: 16,
        maxVertexUniformVectors: 4096,
        maxVaryingVectors: 31,
        maxCombinedTextureImageUnits: 32,
        maxVertexTextureImageUnits: 16,
        maxTextureImageUnits: 16,
        maxFragmentUniformVectors: 1024,
        maxCubeMapTextureSize: 16384,
        maxRenderbufferSize: 16384,
        aliasedLineWidthRange: [1, 1],
        aliasedPointSizeRange: [1, 255]
      },
      timezone: { offset: -480, zone: 'America/Los_Angeles' },
      doNotTrack: null,
      connection: { effectiveType: '4g', rtt: 50, downlink: 10 },
      fonts: ['Arial', 'Arial Black', 'Comic Sans MS', 'Courier New', 'Georgia', 'Helvetica', 'Helvetica Neue', 'Impact', 'Lucida Grande', 'Monaco', 'Palatino', 'Tahoma', 'Times New Roman', 'Trebuchet MS', 'Verdana'],
      voiceCount: 67,
      mediaDevices: { audioinput: 1, videoinput: 1, audiooutput: 1 },
      battery: { charging: false, chargingTime: Infinity, dischargingTime: 36000, level: 0.88 },
      audioParams: { baseLatency: 0.005, outputLatency: 0.005, sampleRate: 44100 }
    },
    {
      id: 'mac_chrome_m2_retina',
      os: 'macOS',
      platform: 'MacIntel',
      userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36',
      appVersion: '5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36',
      vendor: 'Google Inc.',
      hardwareConcurrency: 8,
      deviceMemory: 16,
      languages: ['en-US', 'en'],
      language: 'en-US',
      maxTouchPoints: 0,
      colorDepth: 30,
      pixelDepth: 30,
      screen: { width: 2560, height: 1440, availWidth: 2560, availHeight: 1415 },
      devicePixelRatio: 2,
      gpu: {
        vendor: 'Google Inc. (Apple)',
        renderer: 'ANGLE (Apple, Apple M2, OpenGL 4.1)',
        maxTextureSize: 16384,
        maxViewportDims: [16384, 16384],
        maxVertexAttribs: 16,
        maxVertexUniformVectors: 4096,
        maxVaryingVectors: 31,
        maxCombinedTextureImageUnits: 32,
        maxVertexTextureImageUnits: 16,
        maxTextureImageUnits: 16,
        maxFragmentUniformVectors: 1024,
        maxCubeMapTextureSize: 16384,
        maxRenderbufferSize: 16384,
        aliasedLineWidthRange: [1, 1],
        aliasedPointSizeRange: [1, 255]
      },
      timezone: { offset: -300, zone: 'America/New_York' },
      doNotTrack: null,
      connection: { effectiveType: '4g', rtt: 50, downlink: 10 },
      fonts: ['Arial', 'Arial Black', 'Comic Sans MS', 'Courier New', 'Georgia', 'Helvetica', 'Helvetica Neue', 'Impact', 'Lucida Grande', 'Monaco', 'Palatino', 'Tahoma', 'Times New Roman', 'Trebuchet MS', 'Verdana'],
      voiceCount: 67,
      mediaDevices: { audioinput: 1, videoinput: 1, audiooutput: 2 },
      battery: { charging: true, chargingTime: 1800, dischargingTime: Infinity, level: 0.76 },
      audioParams: { baseLatency: 0.005, outputLatency: 0.005, sampleRate: 48000 }
    },
    {
      id: 'mac_chrome_m3pro_retina',
      os: 'macOS',
      platform: 'MacIntel',
      userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36',
      appVersion: '5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36',
      vendor: 'Google Inc.',
      hardwareConcurrency: 12,
      deviceMemory: 18,
      languages: ['en-GB', 'en'],
      language: 'en-GB',
      maxTouchPoints: 0,
      colorDepth: 30,
      pixelDepth: 30,
      screen: { width: 1920, height: 1080, availWidth: 1920, availHeight: 1055 },
      devicePixelRatio: 2,
      gpu: {
        vendor: 'Google Inc. (Apple)',
        renderer: 'ANGLE (Apple, Apple M3 Pro, OpenGL 4.1)',
        maxTextureSize: 16384,
        maxViewportDims: [16384, 16384],
        maxVertexAttribs: 16,
        maxVertexUniformVectors: 4096,
        maxVaryingVectors: 31,
        maxCombinedTextureImageUnits: 32,
        maxVertexTextureImageUnits: 16,
        maxTextureImageUnits: 16,
        maxFragmentUniformVectors: 1024,
        maxCubeMapTextureSize: 16384,
        maxRenderbufferSize: 16384,
        aliasedLineWidthRange: [1, 1],
        aliasedPointSizeRange: [1, 255]
      },
      timezone: { offset: 0, zone: 'Europe/London' },
      doNotTrack: null,
      connection: { effectiveType: '4g', rtt: 50, downlink: 10 },
      fonts: ['Arial', 'Arial Black', 'Comic Sans MS', 'Courier New', 'Georgia', 'Helvetica', 'Helvetica Neue', 'Impact', 'Lucida Grande', 'Monaco', 'Palatino', 'Tahoma', 'Times New Roman', 'Trebuchet MS', 'Verdana'],
      voiceCount: 67,
      mediaDevices: { audioinput: 1, videoinput: 1, audiooutput: 1 },
      battery: { charging: false, chargingTime: Infinity, dischargingTime: 28800, level: 0.92 },
      audioParams: { baseLatency: 0.005, outputLatency: 0.005, sampleRate: 48000 }
    },

    // ═══════════════════════════════════════════════════════
    // macOS + Intel GPU (older Macs)
    // ═══════════════════════════════════════════════════════
    {
      id: 'mac_chrome_iris_plus',
      os: 'macOS',
      platform: 'MacIntel',
      userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36',
      appVersion: '5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36',
      vendor: 'Google Inc.',
      hardwareConcurrency: 8,
      deviceMemory: 8,
      languages: ['en-US', 'en'],
      language: 'en-US',
      maxTouchPoints: 0,
      colorDepth: 24,
      pixelDepth: 24,
      screen: { width: 1440, height: 900, availWidth: 1440, availHeight: 875 },
      devicePixelRatio: 2,
      gpu: {
        vendor: 'Google Inc. (Intel)',
        renderer: 'ANGLE (Intel, Intel(R) Iris(TM) Plus Graphics 655 OpenGL 4.1)',
        maxTextureSize: 16384,
        maxViewportDims: [16384, 16384],
        maxVertexAttribs: 16,
        maxVertexUniformVectors: 4096,
        maxVaryingVectors: 31,
        maxCombinedTextureImageUnits: 32,
        maxVertexTextureImageUnits: 16,
        maxTextureImageUnits: 16,
        maxFragmentUniformVectors: 1024,
        maxCubeMapTextureSize: 16384,
        maxRenderbufferSize: 16384,
        aliasedLineWidthRange: [1, 1],
        aliasedPointSizeRange: [1, 255]
      },
      timezone: { offset: -480, zone: 'America/Los_Angeles' },
      doNotTrack: null,
      connection: { effectiveType: '4g', rtt: 100, downlink: 5 },
      fonts: ['Arial', 'Arial Black', 'Comic Sans MS', 'Courier New', 'Georgia', 'Helvetica', 'Helvetica Neue', 'Impact', 'Lucida Grande', 'Monaco', 'Palatino', 'Tahoma', 'Times New Roman', 'Trebuchet MS', 'Verdana'],
      voiceCount: 67,
      mediaDevices: { audioinput: 1, videoinput: 1, audiooutput: 1 },
      battery: { charging: false, chargingTime: Infinity, dischargingTime: 14400, level: 0.68 },
      audioParams: { baseLatency: 0.01, outputLatency: 0.01, sampleRate: 44100 }
    },
    {
      id: 'mac_safari_m1',
      os: 'macOS',
      platform: 'MacIntel',
      userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15',
      appVersion: '5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15',
      vendor: 'Apple Computer, Inc.',
      hardwareConcurrency: 8,
      deviceMemory: 8,
      languages: ['en-US'],
      language: 'en-US',
      maxTouchPoints: 0,
      colorDepth: 30,
      pixelDepth: 30,
      screen: { width: 1920, height: 1080, availWidth: 1920, availHeight: 1055 },
      devicePixelRatio: 2,
      gpu: {
        vendor: 'Apple Inc.',
        renderer: 'Apple GPU',
        maxTextureSize: 16384,
        maxViewportDims: [16384, 16384],
        maxVertexAttribs: 16,
        maxVertexUniformVectors: 4096,
        maxVaryingVectors: 31,
        maxCombinedTextureImageUnits: 32,
        maxVertexTextureImageUnits: 16,
        maxTextureImageUnits: 16,
        maxFragmentUniformVectors: 1024,
        maxCubeMapTextureSize: 16384,
        maxRenderbufferSize: 16384,
        aliasedLineWidthRange: [1, 1],
        aliasedPointSizeRange: [1, 255]
      },
      timezone: { offset: -300, zone: 'America/New_York' },
      doNotTrack: null,
      connection: { effectiveType: '4g', rtt: 50, downlink: 10 },
      fonts: ['Arial', 'Arial Black', 'Comic Sans MS', 'Courier New', 'Georgia', 'Helvetica', 'Helvetica Neue', 'Impact', 'Lucida Grande', 'Monaco', 'Palatino', 'Tahoma', 'Times New Roman', 'Trebuchet MS', 'Verdana'],
      voiceCount: 67,
      mediaDevices: { audioinput: 1, videoinput: 1, audiooutput: 1 },
      battery: { charging: false, chargingTime: Infinity, dischargingTime: 32000, level: 0.95 },
      audioParams: { baseLatency: 0.005, outputLatency: 0.005, sampleRate: 44100 }
    },

    // ═══════════════════════════════════════════════════════
    // LINUX + MESA/INTEL
    // ═══════════════════════════════════════════════════════
    {
      id: 'linux_chrome_mesa_intel',
      os: 'Linux',
      platform: 'Linux x86_64',
      userAgent: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36',
      appVersion: '5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36',
      vendor: 'Google Inc.',
      hardwareConcurrency: 8,
      deviceMemory: 8,
      languages: ['en-US', 'en'],
      language: 'en-US',
      maxTouchPoints: 0,
      colorDepth: 24,
      pixelDepth: 24,
      screen: { width: 1920, height: 1080, availWidth: 1920, availHeight: 1053 },
      devicePixelRatio: 1,
      gpu: {
        vendor: 'Google Inc. (Intel)',
        renderer: 'ANGLE (Intel, Mesa Intel(R) UHD Graphics 630 (CFL GT2), OpenGL 4.6)',
        maxTextureSize: 16384,
        maxViewportDims: [16384, 16384],
        maxVertexAttribs: 16,
        maxVertexUniformVectors: 4096,
        maxVaryingVectors: 32,
        maxCombinedTextureImageUnits: 32,
        maxVertexTextureImageUnits: 16,
        maxTextureImageUnits: 16,
        maxFragmentUniformVectors: 1024,
        maxCubeMapTextureSize: 16384,
        maxRenderbufferSize: 16384,
        aliasedLineWidthRange: [1, 7.375],
        aliasedPointSizeRange: [1, 255]
      },
      timezone: { offset: -300, zone: 'America/New_York' },
      doNotTrack: 'unspecified',
      connection: { effectiveType: '4g', rtt: 50, downlink: 10 },
      fonts: ['Arial', 'Courier New', 'DejaVu Sans', 'DejaVu Serif', 'FreeMono', 'FreeSans', 'Liberation Mono', 'Liberation Sans', 'Liberation Serif', 'Noto Sans', 'Times New Roman', 'Ubuntu'],
      voiceCount: 0,
      mediaDevices: { audioinput: 1, videoinput: 0, audiooutput: 1 },
      battery: { charging: true, chargingTime: 0, dischargingTime: Infinity, level: 1.0 },
      audioParams: { baseLatency: 0.005, outputLatency: 0.005, sampleRate: 48000 }
    },
    {
      id: 'linux_chrome_nvidia',
      os: 'Linux',
      platform: 'Linux x86_64',
      userAgent: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36',
      appVersion: '5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36',
      vendor: 'Google Inc.',
      hardwareConcurrency: 16,
      deviceMemory: 32,
      languages: ['en-US', 'en'],
      language: 'en-US',
      maxTouchPoints: 0,
      colorDepth: 24,
      pixelDepth: 24,
      screen: { width: 2560, height: 1440, availWidth: 2560, availHeight: 1413 },
      devicePixelRatio: 1,
      gpu: {
        vendor: 'Google Inc. (NVIDIA)',
        renderer: 'ANGLE (NVIDIA, NVIDIA GeForce RTX 3090/PCIe/SSE2, OpenGL 4.6.0)',
        maxTextureSize: 16384,
        maxViewportDims: [32768, 32768],
        maxVertexAttribs: 16,
        maxVertexUniformVectors: 4096,
        maxVaryingVectors: 32,
        maxCombinedTextureImageUnits: 32,
        maxVertexTextureImageUnits: 16,
        maxTextureImageUnits: 16,
        maxFragmentUniformVectors: 1024,
        maxCubeMapTextureSize: 16384,
        maxRenderbufferSize: 16384,
        aliasedLineWidthRange: [1, 7.375],
        aliasedPointSizeRange: [1, 1024]
      },
      timezone: { offset: -480, zone: 'America/Los_Angeles' },
      doNotTrack: null,
      connection: { effectiveType: '4g', rtt: 50, downlink: 10 },
      fonts: ['Arial', 'Courier New', 'DejaVu Sans', 'DejaVu Serif', 'FreeMono', 'FreeSans', 'Liberation Mono', 'Liberation Sans', 'Liberation Serif', 'Noto Sans', 'Times New Roman', 'Ubuntu'],
      voiceCount: 0,
      mediaDevices: { audioinput: 1, videoinput: 1, audiooutput: 1 },
      battery: { charging: true, chargingTime: 0, dischargingTime: Infinity, level: 1.0 },
      audioParams: { baseLatency: 0.005, outputLatency: 0.005, sampleRate: 48000 }
    },
    {
      id: 'linux_firefox_mesa_amd',
      os: 'Linux',
      platform: 'Linux x86_64',
      userAgent: 'Mozilla/5.0 (X11; Linux x86_64; rv:127.0) Gecko/20100101 Firefox/127.0',
      appVersion: '5.0 (X11)',
      vendor: '',
      hardwareConcurrency: 12,
      deviceMemory: 8,
      languages: ['en-US', 'en'],
      language: 'en-US',
      maxTouchPoints: 0,
      colorDepth: 24,
      pixelDepth: 24,
      screen: { width: 1920, height: 1080, availWidth: 1920, availHeight: 1053 },
      devicePixelRatio: 1,
      gpu: {
        vendor: 'Google Inc. (AMD)',
        renderer: 'ANGLE (AMD, AMD Radeon RX 6600 XT, OpenGL 4.6)',
        maxTextureSize: 16384,
        maxViewportDims: [16384, 16384],
        maxVertexAttribs: 16,
        maxVertexUniformVectors: 4096,
        maxVaryingVectors: 32,
        maxCombinedTextureImageUnits: 32,
        maxVertexTextureImageUnits: 16,
        maxTextureImageUnits: 16,
        maxFragmentUniformVectors: 1024,
        maxCubeMapTextureSize: 16384,
        maxRenderbufferSize: 16384,
        aliasedLineWidthRange: [1, 7.375],
        aliasedPointSizeRange: [1, 1024]
      },
      timezone: { offset: -60, zone: 'Europe/Berlin' },
      doNotTrack: 'unspecified',
      connection: { effectiveType: '4g', rtt: 100, downlink: 5 },
      fonts: ['Arial', 'Courier New', 'DejaVu Sans', 'DejaVu Serif', 'FreeMono', 'FreeSans', 'Liberation Mono', 'Liberation Sans', 'Liberation Serif', 'Noto Sans', 'Times New Roman', 'Ubuntu'],
      voiceCount: 0,
      mediaDevices: { audioinput: 1, videoinput: 0, audiooutput: 1 },
      battery: { charging: true, chargingTime: 0, dischargingTime: Infinity, level: 1.0 },
      audioParams: { baseLatency: 0.01, outputLatency: 0.01, sampleRate: 48000 }
    },

    // ═══════════════════════════════════════════════════════
    // WINDOWS — Additional language/region variants
    // ═══════════════════════════════════════════════════════
    {
      id: 'win_chrome_rtx2060_jp',
      os: 'Windows',
      platform: 'Win32',
      userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36',
      appVersion: '5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36',
      vendor: 'Google Inc.',
      hardwareConcurrency: 8,
      deviceMemory: 16,
      languages: ['ja-JP', 'ja', 'en-US'],
      language: 'ja-JP',
      maxTouchPoints: 0,
      colorDepth: 24,
      pixelDepth: 24,
      screen: { width: 1920, height: 1080, availWidth: 1920, availHeight: 1040 },
      devicePixelRatio: 1,
      gpu: {
        vendor: 'Google Inc. (NVIDIA)',
        renderer: 'ANGLE (NVIDIA, NVIDIA GeForce RTX 2060 Direct3D11 vs_5_0 ps_5_0, D3D11)',
        maxTextureSize: 16384,
        maxViewportDims: [32768, 32768],
        maxVertexAttribs: 16,
        maxVertexUniformVectors: 4096,
        maxVaryingVectors: 32,
        maxCombinedTextureImageUnits: 32,
        maxVertexTextureImageUnits: 16,
        maxTextureImageUnits: 16,
        maxFragmentUniformVectors: 1024,
        maxCubeMapTextureSize: 16384,
        maxRenderbufferSize: 16384,
        aliasedLineWidthRange: [1, 1],
        aliasedPointSizeRange: [1, 1024]
      },
      timezone: { offset: -540, zone: 'Asia/Tokyo' },
      doNotTrack: null,
      connection: { effectiveType: '4g', rtt: 50, downlink: 10 },
      fonts: ['Arial', 'Calibri', 'Cambria', 'Comic Sans MS', 'Consolas', 'Courier New', 'Georgia', 'Impact', 'MS Gothic', 'MS Mincho', 'Meiryo', 'Segoe UI', 'Tahoma', 'Times New Roman', 'Verdana', 'Yu Gothic'],
      voiceCount: 5,
      mediaDevices: { audioinput: 1, videoinput: 1, audiooutput: 2 },
      battery: { charging: true, chargingTime: 0, dischargingTime: Infinity, level: 1.0 },
      audioParams: { baseLatency: 0.01, outputLatency: 0.01, sampleRate: 48000 }
    },
    {
      id: 'win_chrome_intel_es',
      os: 'Windows',
      platform: 'Win32',
      userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36',
      appVersion: '5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36',
      vendor: 'Google Inc.',
      hardwareConcurrency: 4,
      deviceMemory: 4,
      languages: ['es-ES', 'es', 'en'],
      language: 'es-ES',
      maxTouchPoints: 0,
      colorDepth: 24,
      pixelDepth: 24,
      screen: { width: 1366, height: 768, availWidth: 1366, availHeight: 728 },
      devicePixelRatio: 1,
      gpu: {
        vendor: 'Google Inc. (Intel)',
        renderer: 'ANGLE (Intel, Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0, D3D11)',
        maxTextureSize: 8192,
        maxViewportDims: [8192, 8192],
        maxVertexAttribs: 16,
        maxVertexUniformVectors: 4096,
        maxVaryingVectors: 32,
        maxCombinedTextureImageUnits: 32,
        maxVertexTextureImageUnits: 16,
        maxTextureImageUnits: 16,
        maxFragmentUniformVectors: 1024,
        maxCubeMapTextureSize: 8192,
        maxRenderbufferSize: 8192,
        aliasedLineWidthRange: [1, 1],
        aliasedPointSizeRange: [1, 1024]
      },
      timezone: { offset: -60, zone: 'Europe/Madrid' },
      doNotTrack: null,
      connection: { effectiveType: '4g', rtt: 150, downlink: 1.5 },
      fonts: ['Arial', 'Calibri', 'Cambria', 'Comic Sans MS', 'Consolas', 'Courier New', 'Georgia', 'Impact', 'Segoe UI', 'Tahoma', 'Times New Roman', 'Trebuchet MS', 'Verdana'],
      voiceCount: 5,
      mediaDevices: { audioinput: 1, videoinput: 1, audiooutput: 1 },
      battery: { charging: false, chargingTime: Infinity, dischargingTime: 7200, level: 0.35 },
      audioParams: { baseLatency: 0.01, outputLatency: 0.02, sampleRate: 44100 }
    },

    // ═══════════════════════════════════════════════════════
    // WINDOWS 11 profiles
    // ═══════════════════════════════════════════════════════
    {
      id: 'win11_chrome_rtx4060_1080p',
      os: 'Windows',
      platform: 'Win32',
      userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36',
      appVersion: '5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36',
      vendor: 'Google Inc.',
      hardwareConcurrency: 8,
      deviceMemory: 16,
      languages: ['en-US', 'en'],
      language: 'en-US',
      maxTouchPoints: 0,
      colorDepth: 24,
      pixelDepth: 24,
      screen: { width: 1920, height: 1080, availWidth: 1920, availHeight: 1032 },
      devicePixelRatio: 1,
      gpu: {
        vendor: 'Google Inc. (NVIDIA)',
        renderer: 'ANGLE (NVIDIA, NVIDIA GeForce RTX 4060 Direct3D11 vs_5_0 ps_5_0, D3D11)',
        maxTextureSize: 16384,
        maxViewportDims: [32768, 32768],
        maxVertexAttribs: 16,
        maxVertexUniformVectors: 4096,
        maxVaryingVectors: 32,
        maxCombinedTextureImageUnits: 32,
        maxVertexTextureImageUnits: 16,
        maxTextureImageUnits: 16,
        maxFragmentUniformVectors: 1024,
        maxCubeMapTextureSize: 16384,
        maxRenderbufferSize: 16384,
        aliasedLineWidthRange: [1, 1],
        aliasedPointSizeRange: [1, 1024]
      },
      timezone: { offset: -300, zone: 'America/New_York' },
      doNotTrack: null,
      connection: { effectiveType: '4g', rtt: 50, downlink: 10 },
      fonts: ['Arial', 'Arial Black', 'Calibri', 'Cambria', 'Comic Sans MS', 'Consolas', 'Courier New', 'Georgia', 'Impact', 'Lucida Console', 'Segoe UI', 'Segoe UI Variable', 'Tahoma', 'Times New Roman', 'Trebuchet MS', 'Verdana'],
      voiceCount: 5,
      mediaDevices: { audioinput: 1, videoinput: 1, audiooutput: 2 },
      battery: { charging: true, chargingTime: 0, dischargingTime: Infinity, level: 1.0 },
      audioParams: { baseLatency: 0.01, outputLatency: 0.01, sampleRate: 48000 }
    },

    // ═══════════════════════════════════════════════════════
    // ANDROID MOBILE PROFILES
    // ═══════════════════════════════════════════════════════
    {
      id: 'android_chrome_pixel',
      os: 'Android',
      platform: 'Linux armv8l',
      userAgent: 'Mozilla/5.0 (Linux; Android 14; Pixel 8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Mobile Safari/537.36',
      appVersion: '5.0 (Linux; Android 14; Pixel 8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Mobile Safari/537.36',
      vendor: 'Google Inc.',
      hardwareConcurrency: 8,
      deviceMemory: 8,
      languages: ['en-US', 'en'],
      language: 'en-US',
      maxTouchPoints: 5,
      colorDepth: 24,
      pixelDepth: 24,
      screen: { width: 412, height: 915, availWidth: 412, availHeight: 857 },
      devicePixelRatio: 2.625,
      gpu: {
        vendor: 'Qualcomm',
        renderer: 'Adreno (TM) 750',
        maxTextureSize: 16384,
        maxViewportDims: [16384, 16384],
        maxVertexAttribs: 16,
        maxVertexUniformVectors: 256,
        maxVaryingVectors: 32,
        maxCombinedTextureImageUnits: 32,
        maxVertexTextureImageUnits: 16,
        maxTextureImageUnits: 16,
        maxFragmentUniformVectors: 224,
        maxCubeMapTextureSize: 16384,
        maxRenderbufferSize: 16384,
        aliasedLineWidthRange: [1, 1],
        aliasedPointSizeRange: [1, 1024]
      },
      timezone: { offset: -300, zone: 'America/New_York' },
      doNotTrack: null,
      connection: { effectiveType: '4g', rtt: 50, downlink: 10 },
      fonts: ['Roboto', 'Droid Sans', 'Noto Sans'],
      voiceCount: 0,
      mediaDevices: { audioinput: 1, videoinput: 2, audiooutput: 1 },
      battery: { charging: false, chargingTime: Infinity, dischargingTime: 18000, level: 0.78 },
      audioParams: { baseLatency: 0.01, outputLatency: 0.02, sampleRate: 48000 }
    },
    {
      id: 'android_chrome_samsung',
      os: 'Android',
      platform: 'Linux armv8l',
      userAgent: 'Mozilla/5.0 (Linux; Android 14; SM-S918B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Mobile Safari/537.36',
      appVersion: '5.0 (Linux; Android 14; SM-S918B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Mobile Safari/537.36',
      vendor: 'Google Inc.',
      hardwareConcurrency: 8,
      deviceMemory: 8,
      languages: ['en-US', 'en'],
      language: 'en-US',
      maxTouchPoints: 5,
      colorDepth: 24,
      pixelDepth: 24,
      screen: { width: 384, height: 854, availWidth: 384, availHeight: 811 },
      devicePixelRatio: 3,
      gpu: {
        vendor: 'ARM',
        renderer: 'Mali-G715 Immortalis MC11',
        maxTextureSize: 8192,
        maxViewportDims: [8192, 8192],
        maxVertexAttribs: 16,
        maxVertexUniformVectors: 256,
        maxVaryingVectors: 15,
        maxCombinedTextureImageUnits: 32,
        maxVertexTextureImageUnits: 16,
        maxTextureImageUnits: 16,
        maxFragmentUniformVectors: 224,
        maxCubeMapTextureSize: 8192,
        maxRenderbufferSize: 8192,
        aliasedLineWidthRange: [1, 1],
        aliasedPointSizeRange: [1, 1024]
      },
      timezone: { offset: -300, zone: 'America/New_York' },
      doNotTrack: null,
      connection: { effectiveType: '4g', rtt: 100, downlink: 5 },
      fonts: ['Roboto', 'Droid Sans', 'Noto Sans'],
      voiceCount: 0,
      mediaDevices: { audioinput: 1, videoinput: 2, audiooutput: 1 },
      battery: { charging: true, chargingTime: 3600, dischargingTime: Infinity, level: 0.62 },
      audioParams: { baseLatency: 0.01, outputLatency: 0.02, sampleRate: 48000 }
    },

    // ═══════════════════════════════════════════════════════
    // iOS MOBILE PROFILES
    // ═══════════════════════════════════════════════════════
    {
      id: 'ios_safari_iphone15',
      os: 'iOS',
      platform: 'iPhone',
      userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Mobile/15E148 Safari/604.1',
      appVersion: '5.0 (iPhone; CPU iPhone OS 17_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Mobile/15E148 Safari/604.1',
      vendor: 'Apple Computer, Inc.',
      hardwareConcurrency: 6,
      deviceMemory: 4,
      languages: ['en-US'],
      language: 'en-US',
      maxTouchPoints: 5,
      colorDepth: 32,
      pixelDepth: 32,
      screen: { width: 393, height: 852, availWidth: 393, availHeight: 852 },
      devicePixelRatio: 3,
      gpu: {
        vendor: 'Apple Inc.',
        renderer: 'Apple GPU',
        maxTextureSize: 8192,
        maxViewportDims: [8192, 8192],
        maxVertexAttribs: 16,
        maxVertexUniformVectors: 1024,
        maxVaryingVectors: 15,
        maxCombinedTextureImageUnits: 32,
        maxVertexTextureImageUnits: 16,
        maxTextureImageUnits: 16,
        maxFragmentUniformVectors: 1024,
        maxCubeMapTextureSize: 8192,
        maxRenderbufferSize: 8192,
        aliasedLineWidthRange: [1, 1],
        aliasedPointSizeRange: [1, 255]
      },
      timezone: { offset: -300, zone: 'America/New_York' },
      doNotTrack: null,
      connection: { effectiveType: '4g', rtt: 50, downlink: 10 },
      fonts: ['Arial', 'Courier New', 'Georgia', 'Helvetica', 'Helvetica Neue', 'Times New Roman', 'Trebuchet MS', 'Verdana'],
      voiceCount: 54,
      mediaDevices: { audioinput: 1, videoinput: 2, audiooutput: 1 },
      battery: { charging: false, chargingTime: Infinity, dischargingTime: 21600, level: 0.72 },
      audioParams: { baseLatency: 0.005, outputLatency: 0.005, sampleRate: 48000 }
    },

    // ═══════════════════════════════════════════════════════
    // Additional Windows variations
    // ═══════════════════════════════════════════════════════
    {
      id: 'win_chrome_rtx2070_pt',
      os: 'Windows',
      platform: 'Win32',
      userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36',
      appVersion: '5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36',
      vendor: 'Google Inc.',
      hardwareConcurrency: 8,
      deviceMemory: 16,
      languages: ['pt-BR', 'pt', 'en-US'],
      language: 'pt-BR',
      maxTouchPoints: 0,
      colorDepth: 24,
      pixelDepth: 24,
      screen: { width: 1920, height: 1080, availWidth: 1920, availHeight: 1040 },
      devicePixelRatio: 1,
      gpu: {
        vendor: 'Google Inc. (NVIDIA)',
        renderer: 'ANGLE (NVIDIA, NVIDIA GeForce RTX 2070 SUPER Direct3D11 vs_5_0 ps_5_0, D3D11)',
        maxTextureSize: 16384,
        maxViewportDims: [32768, 32768],
        maxVertexAttribs: 16,
        maxVertexUniformVectors: 4096,
        maxVaryingVectors: 32,
        maxCombinedTextureImageUnits: 32,
        maxVertexTextureImageUnits: 16,
        maxTextureImageUnits: 16,
        maxFragmentUniformVectors: 1024,
        maxCubeMapTextureSize: 16384,
        maxRenderbufferSize: 16384,
        aliasedLineWidthRange: [1, 1],
        aliasedPointSizeRange: [1, 1024]
      },
      timezone: { offset: 180, zone: 'America/Sao_Paulo' },
      doNotTrack: null,
      connection: { effectiveType: '4g', rtt: 100, downlink: 5 },
      fonts: ['Arial', 'Calibri', 'Cambria', 'Comic Sans MS', 'Consolas', 'Courier New', 'Georgia', 'Impact', 'Segoe UI', 'Tahoma', 'Times New Roman', 'Trebuchet MS', 'Verdana'],
      voiceCount: 5,
      mediaDevices: { audioinput: 1, videoinput: 1, audiooutput: 1 },
      battery: { charging: true, chargingTime: 0, dischargingTime: Infinity, level: 1.0 },
      audioParams: { baseLatency: 0.01, outputLatency: 0.01, sampleRate: 48000 }
    },
    {
      id: 'win_chrome_rx5700xt_zh',
      os: 'Windows',
      platform: 'Win32',
      userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36',
      appVersion: '5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36',
      vendor: 'Google Inc.',
      hardwareConcurrency: 12,
      deviceMemory: 16,
      languages: ['zh-CN', 'zh', 'en-US'],
      language: 'zh-CN',
      maxTouchPoints: 0,
      colorDepth: 24,
      pixelDepth: 24,
      screen: { width: 1920, height: 1080, availWidth: 1920, availHeight: 1040 },
      devicePixelRatio: 1.25,
      gpu: {
        vendor: 'Google Inc. (AMD)',
        renderer: 'ANGLE (AMD, AMD Radeon RX 5700 XT Direct3D11 vs_5_0 ps_5_0, D3D11)',
        maxTextureSize: 16384,
        maxViewportDims: [16384, 16384],
        maxVertexAttribs: 16,
        maxVertexUniformVectors: 4096,
        maxVaryingVectors: 32,
        maxCombinedTextureImageUnits: 32,
        maxVertexTextureImageUnits: 16,
        maxTextureImageUnits: 16,
        maxFragmentUniformVectors: 1024,
        maxCubeMapTextureSize: 16384,
        maxRenderbufferSize: 16384,
        aliasedLineWidthRange: [1, 1],
        aliasedPointSizeRange: [1, 1024]
      },
      timezone: { offset: -480, zone: 'Asia/Shanghai' },
      doNotTrack: null,
      connection: { effectiveType: '4g', rtt: 50, downlink: 10 },
      fonts: ['Arial', 'Calibri', 'Cambria', 'Comic Sans MS', 'Consolas', 'Courier New', 'Georgia', 'Impact', 'Microsoft YaHei', 'SimHei', 'SimSun', 'Segoe UI', 'Tahoma', 'Times New Roman', 'Verdana'],
      voiceCount: 5,
      mediaDevices: { audioinput: 1, videoinput: 1, audiooutput: 2 },
      battery: { charging: true, chargingTime: 0, dischargingTime: Infinity, level: 1.0 },
      audioParams: { baseLatency: 0.01, outputLatency: 0.01, sampleRate: 48000 }
    }
  ];

  // Pre-built profile categories for quick selection
  const PROFILE_CATEGORIES = {
    'Windows Desktop': PROFILES.filter(p => p.os === 'Windows'),
    'Mac Desktop': PROFILES.filter(p => p.os === 'macOS'),
    'Linux Desktop': PROFILES.filter(p => p.os === 'Linux'),
    'Android Mobile': PROFILES.filter(p => p.os === 'Android'),
    'iOS Mobile': PROFILES.filter(p => p.os === 'iOS')
  };

  return {
    PROFILES: PROFILES,
    CATEGORIES: PROFILE_CATEGORIES,
    getById: function(id) {
      return PROFILES.find(function(p) { return p.id === id; });
    },
    getRandom: function(rng) {
      if (rng) return rng.randomChoice(PROFILES);
      return PROFILES[Math.floor(Math.random() * PROFILES.length)];
    },
    getRandomFromCategory: function(category, rng) {
      const cat = PROFILE_CATEGORIES[category];
      if (!cat || cat.length === 0) return this.getRandom(rng);
      if (rng) return rng.randomChoice(cat);
      return cat[Math.floor(Math.random() * cat.length)];
    }
  };
})();
